/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.uva.sga.visao;

import br.uva.sga.controle.dao.PessoaDAO;
import br.uva.sga.modelo.Pessoa;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author lele2
 */
public class AtualizarDados extends javax.swing.JFrame {

    /**
     * Creates new form AtualizarDados
     */
    public AtualizarDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlabel_digiteseusdados = new javax.swing.JLabel();
        jlabel_nome = new javax.swing.JLabel();
        jtextfield_nome = new javax.swing.JTextField();
        jlabel_senha = new javax.swing.JLabel();
        jtextfield_senha = new javax.swing.JPasswordField();
        jlabel_email = new javax.swing.JLabel();
        jtextfield_email = new javax.swing.JTextField();
        jlabel_telefone = new javax.swing.JLabel();
        jtextfield_telefone = new javax.swing.JTextField();
        jlabel_idade = new javax.swing.JLabel();
        jtextfield_idade = new javax.swing.JTextField();
        jlabel_cargo = new javax.swing.JLabel();
        jbutton_deletarconta = new javax.swing.JButton();
        jbutton_atualizarconta = new javax.swing.JButton();
        jlabel_dangerzone = new javax.swing.JLabel();
        jradio_fiscal = new javax.swing.JRadioButton();
        jradio_fiscalgaragem = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabel_digiteseusdados.setForeground(new java.awt.Color(61, 73, 186));
        jlabel_digiteseusdados.setText("Digite seus dados");
        jlabel_digiteseusdados.setName("jlabel_digiteseusdados"); // NOI18N

        jlabel_nome.setText("Nome");
        jlabel_nome.setName("jlabel_nome"); // NOI18N

        jtextfield_nome.setName("jtextfield_nome"); // NOI18N

        jlabel_senha.setText("Senha");
        jlabel_senha.setName("jlabel_senha"); // NOI18N

        jtextfield_senha.setName("jtextfield_senha"); // NOI18N
        jtextfield_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_senhaActionPerformed(evt);
            }
        });

        jlabel_email.setText("Email");
        jlabel_email.setName("jlabel_email"); // NOI18N

        jtextfield_email.setName("jtextfield_email"); // NOI18N
        jtextfield_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_emailActionPerformed(evt);
            }
        });

        jlabel_telefone.setText("Telefone");
        jlabel_telefone.setName("jlabel_telefone"); // NOI18N

        jtextfield_telefone.setName("jtextfield_telefone"); // NOI18N

        jlabel_idade.setText("Idade");
        jlabel_idade.setName("jlabel_idade"); // NOI18N

        jtextfield_idade.setName("jtextfield_idade"); // NOI18N

        jlabel_cargo.setText("Cargo");
        jlabel_cargo.setName("jlabel_cargo"); // NOI18N

        jbutton_deletarconta.setText("Deletar Conta");
        jbutton_deletarconta.setName("jbutton_deletarconta"); // NOI18N

        jbutton_atualizarconta.setText("Atualizar Conta");
        jbutton_atualizarconta.setName("jbutton_atualizarconta"); // NOI18N

        jlabel_dangerzone.setForeground(new java.awt.Color(255, 0, 0));
        jlabel_dangerzone.setText("Danger Zone");
        jlabel_dangerzone.setName("jlabel_dangerzone"); // NOI18N

        jradio_fiscal.setText("Fiscal");
        jradio_fiscal.setName("jradio_fiscal"); // NOI18N

        jradio_fiscalgaragem.setText("Fiscal de Garagem");
        jradio_fiscalgaragem.setName("jradio_fiscalgaragem"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\davin\\Downloads\\PaulitosBUS_semFundo.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbutton_atualizarconta)
                    .addComponent(jlabel_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextfield_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlabel_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlabel_email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtextfield_email, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(jtextfield_nome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbutton_deletarconta)
                    .addComponent(jradio_fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradio_fiscalgaragem)
                    .addComponent(jlabel_dangerzone)
                    .addComponent(jlabel_telefone)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtextfield_telefone)
                            .addComponent(jlabel_idade)
                            .addComponent(jtextfield_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jlabel_digiteseusdados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel_nome)
                            .addComponent(jlabel_telefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextfield_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlabel_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextfield_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlabel_senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextfield_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlabel_digiteseusdados)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtextfield_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlabel_idade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtextfield_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(jlabel_cargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jradio_fiscal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jradio_fiscalgaragem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabel_dangerzone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton_deletarconta)
                    .addComponent(jbutton_atualizarconta))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfield_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_emailActionPerformed

    private void jtextfield_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_senhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbutton_atualizarconta;
    private javax.swing.JButton jbutton_deletarconta;
    private javax.swing.JLabel jlabel_cargo;
    private javax.swing.JLabel jlabel_dangerzone;
    private javax.swing.JLabel jlabel_digiteseusdados;
    private javax.swing.JLabel jlabel_email;
    private javax.swing.JLabel jlabel_idade;
    private javax.swing.JLabel jlabel_nome;
    private javax.swing.JLabel jlabel_senha;
    private javax.swing.JLabel jlabel_telefone;
    private javax.swing.JRadioButton jradio_fiscal;
    private javax.swing.JRadioButton jradio_fiscalgaragem;
    private javax.swing.JTextField jtextfield_email;
    private javax.swing.JTextField jtextfield_idade;
    private javax.swing.JTextField jtextfield_nome;
    private javax.swing.JPasswordField jtextfield_senha;
    private javax.swing.JTextField jtextfield_telefone;
    // End of variables declaration//GEN-END:variables

    public void botaoupdate(Pessoa pessoa){
        getJbutton_atualizarconta().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    pessoa.setNome(getJtextfield_nome().getText());
                    pessoa.setEmail(getJtextfield_email().getText());
                    pessoa.setTelefone(getJtextfield_telefone().getText());
                    pessoa.setIdade(Integer.parseInt(getJtextfield_idade().getText()));
                    String senhaUsuario = "";
                    for (int i = 0; i < getJtextfield_senha().getPassword().length; i++) {
                        senhaUsuario += getJtextfield_senha().getPassword()[i];
                    }
                    pessoa.setSenha(senhaUsuario);
                    if (getJradio_fiscal().isSelected()) {
                        pessoa.setCargo("Fiscal");
                    }else {
                        pessoa.setCargo("Fiscal de Garagem");
                    }
                    PessoaDAO pessoaDAO = new PessoaDAO();
                    pessoaDAO.update(pessoa);
                    getContentPane().setVisible(false);
                    Configuracoes configuracoes = new Configuracoes();
                    configuracoes.menu(pessoa);
                    JComponent comp = (JComponent) e.getSource();
                    Window win = SwingUtilities.getWindowAncestor(comp);
                    win.dispose();


                }catch(Exception error){
                     error.printStackTrace();
                }
            }

        });
    }

    public void botaodelete(Pessoa pessoa){
        getJbutton_deletarconta().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try{
                    PessoaDAO pessoaDeleteDAO = new PessoaDAO();
                    pessoaDeleteDAO.delete(pessoa);
                    System.exit(0);
                }catch (Exception error){
                    error.printStackTrace();
                }
            }
        });
    }



    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JButton getJbutton_atualizarconta() {
        return jbutton_atualizarconta;
    }

    public JButton getJbutton_deletarconta() {
        return jbutton_deletarconta;
    }

    public JLabel getJlabel_cargo() {
        return jlabel_cargo;
    }

    public JLabel getJlabel_dangerzone() {
        return jlabel_dangerzone;
    }

    public JLabel getJlabel_digiteseusdados() {
        return jlabel_digiteseusdados;
    }

    public JLabel getJlabel_email() {
        return jlabel_email;
    }

    public JLabel getJlabel_idade() {
        return jlabel_idade;
    }

    public JLabel getJlabel_nome() {
        return jlabel_nome;
    }

    public JLabel getJlabel_senha() {
        return jlabel_senha;
    }

    public JLabel getJlabel_telefone() {
        return jlabel_telefone;
    }

    public JRadioButton getJradio_fiscal() {
        return jradio_fiscal;
    }

    public JRadioButton getJradio_fiscalgaragem() {
        return jradio_fiscalgaragem;
    }

    public JTextField getJtextfield_email() {
        return jtextfield_email;
    }

    public JTextField getJtextfield_idade() {
        return jtextfield_idade;
    }

    public JTextField getJtextfield_nome() {
        return jtextfield_nome;
    }

    public JPasswordField getJtextfield_senha() {
        return jtextfield_senha;
    }

    public JTextField getJtextfield_telefone() {
        return jtextfield_telefone;
    }
}
