/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.uva.sga.visao;

import br.uva.sga.modelo.Pessoa;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author 20212101161
 */
public class LancamentoFiscalInicial extends javax.swing.JFrame {

    /**
     * Creates new form LancamentoFiscalInicial
     */
    public LancamentoFiscalInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_lancamentosistema = new javax.swing.JLabel();
        label_horariosaida = new javax.swing.JLabel();
        jtextfield_horariosaida = new javax.swing.JTextField();
        label_numerecaoonibus = new javax.swing.JLabel();
        jtextfield_numeracaoonibus = new javax.swing.JTextField();
        label_numeracaoroleta = new javax.swing.JLabel();
        jtextfield_numereacaoroleta = new javax.swing.JTextField();
        jbutton_lancar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_lancamentosistema.setText("Lançamento Sistema");
        label_lancamentosistema.setName("label_lancamentosistema"); // NOI18N

        label_horariosaida.setText("Hórario de Saída:");
        label_horariosaida.setName("label_horariosaida"); // NOI18N

        jtextfield_horariosaida.setName("jtextfield_horariosaida"); // NOI18N
        jtextfield_horariosaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_horariosaidaActionPerformed(evt);
            }
        });

        label_numerecaoonibus.setText("Númeração do Ônibus:");
        label_numerecaoonibus.setName("label_numerecaoonibus"); // NOI18N

        jtextfield_numeracaoonibus.setName("jtextfield_numeracaoonibus"); // NOI18N
        jtextfield_numeracaoonibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_numeracaoonibusActionPerformed(evt);
            }
        });

        label_numeracaoroleta.setText("Númeração Roleta:");
        label_numeracaoroleta.setName("label_numeracaoroleta"); // NOI18N

        jtextfield_numereacaoroleta.setText("                               ");
        jtextfield_numereacaoroleta.setName("jtextfield_numereacaoroleta"); // NOI18N
        jtextfield_numereacaoroleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_numereacaoroletaActionPerformed(evt);
            }
        });

        jbutton_lancar.setText("Lançar");
        jbutton_lancar.setName("jbutton_lancar"); // NOI18N
        jbutton_lancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_lancarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/paulitos/Documents/Cursos/Cursos_Backup_30-04-22/Faculdade/3º periodo/POO/A4_POO/Trabalho_POO_Versão_Final/mavenproject1/Funcionarios-main/src/main/java/br/uva/sga/visao/Icones/PaulitosBUS_semFundo.png"));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_numerecaoonibus)
                                .addComponent(jtextfield_numeracaoonibus, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtextfield_horariosaida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_horariosaida))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtextfield_numereacaoroleta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_numeracaoroleta))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jbutton_lancar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(label_lancamentosistema)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_lancamentosistema)
                        .addGap(31, 31, 31)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_numeracaoroleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextfield_numereacaoroleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_horariosaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextfield_horariosaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(label_numerecaoonibus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jtextfield_numeracaoonibus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbutton_lancar)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfield_horariosaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_horariosaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_horariosaidaActionPerformed

    private void jtextfield_numeracaoonibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_numeracaoonibusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_numeracaoonibusActionPerformed

    private void jtextfield_numereacaoroletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_numereacaoroletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_numereacaoroletaActionPerformed

    private void jbutton_lancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_lancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_lancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancamentoFiscalInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancamentoFiscalInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancamentoFiscalInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancamentoFiscalInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LancamentoFiscalInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbutton_lancar;
    private javax.swing.JTextField jtextfield_horariosaida;
    private javax.swing.JTextField jtextfield_numeracaoonibus;
    private javax.swing.JTextField jtextfield_numereacaoroleta;
    private javax.swing.JLabel label_horariosaida;
    private javax.swing.JLabel label_lancamentosistema;
    private javax.swing.JLabel label_numeracaoroleta;
    private javax.swing.JLabel label_numerecaoonibus;
    // End of variables declaration//GEN-END:variables

    public void lancamento(Pessoa pessoa){
        getJbutton_lancar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Configuracoes configuracoes = new Configuracoes();
                configuracoes.menu(pessoa);
                JComponent comp = (JComponent) e.getSource();
                Window win = SwingUtilities.getWindowAncestor(comp);
                win.dispose();
            }
        });

    }

    public JButton getJbutton_lancar() {
        return jbutton_lancar;
    }

    public JTextField getJtextfield_horariosaida() {
        return jtextfield_horariosaida;
    }

    public JTextField getJtextfield_numeracaoonibus() {
        return jtextfield_numeracaoonibus;
    }

    public JTextField getJtextfield_numereacaoroleta() {
        return jtextfield_numereacaoroleta;
    }

    public JLabel getLabel_horariosaida() {
        return label_horariosaida;
    }

    public JLabel getLabel_lancamentosistema() {
        return label_lancamentosistema;
    }

    public JLabel getLabel_numeracaoroleta() {
        return label_numeracaoroleta;
    }

    public JLabel getLabel_numerecaoonibus() {
        return label_numerecaoonibus;
    }
}
