/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.uva.sga.visao;

import br.uva.sga.modelo.Pessoa;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author 20212101161
 */
public class LancamentoFiscalFinal extends javax.swing.JFrame {

    /**
     * Creates new form LancamentoFiscal
     */
    public LancamentoFiscalFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label_lancamento = new javax.swing.JLabel();
        label_horariochegada = new javax.swing.JLabel();
        jtextfield_horariochegada = new javax.swing.JTextField();
        label_horarioonibus = new javax.swing.JLabel();
        jtextfield_numeroonibus = new javax.swing.JTextField();
        label_numeracaoroleta = new javax.swing.JLabel();
        jtextfield_numeracaoroleta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jradio_houvereclamacao = new javax.swing.JRadioButton();
        jbutton_lancar = new javax.swing.JToggleButton();
        jtextfield_quantas = new javax.swing.JTextField();
        label_quantas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_lancamento.setText("Lançamento no Sistema");
        label_lancamento.setName("label_lancamento"); // NOI18N

        label_horariochegada.setText("Horário de Chegada:");
        label_horariochegada.setToolTipText("");
        label_horariochegada.setName("label_horariochegada"); // NOI18N

        jtextfield_horariochegada.setName("jtextfield_horariochegada"); // NOI18N
        jtextfield_horariochegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_horariochegadaActionPerformed(evt);
            }
        });

        label_horarioonibus.setText("Número do ônibus:");
        label_horarioonibus.setName("label_horarioonibus"); // NOI18N

        jtextfield_numeroonibus.setName("jtextfield_numeroonibus"); // NOI18N
        jtextfield_numeroonibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_numeroonibusActionPerformed(evt);
            }
        });

        label_numeracaoroleta.setText("Númeração roleta:");
        label_numeracaoroleta.setName("label_numeracaoroleta"); // NOI18N

        jtextfield_numeracaoroleta.setName("jtextfield_numeracaoroleta"); // NOI18N
        jtextfield_numeracaoroleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_numeracaoroletaActionPerformed(evt);
            }
        });

        jLabel5.setName("textoNumeracaoRoleta"); // NOI18N

        jradio_houvereclamacao.setText("Houve Reclamação?");
        jradio_houvereclamacao.setName("jradio_houvereclamacao"); // NOI18N
        jradio_houvereclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradio_houvereclamacaoActionPerformed(evt);
            }
        });

        jbutton_lancar.setText("Lançar");
        jbutton_lancar.setName("jbutton_lancar"); // NOI18N
        jbutton_lancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_lancarActionPerformed(evt);
            }
        });

        jtextfield_quantas.setName("jtextfield_quantas"); // NOI18N
        jtextfield_quantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_quantasActionPerformed(evt);
            }
        });

        label_quantas.setText("Quantas?");
        label_quantas.setName("label_quantas"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/paulitos/Documents/Cursos/Cursos_Backup_30-04-22/Faculdade/3º periodo/POO/A4_POO/Trabalho_POO_Versão_Final/mavenproject1/Funcionarios-main/src/main/java/br/uva/sga/visao/Icones/PaulitosBUS_semFundo.png"));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jbutton_lancar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtextfield_numeroonibus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jradio_houvereclamacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(label_quantas))
                                    .addComponent(jtextfield_quantas, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_horarioonibus))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtextfield_horariochegada, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(label_horariochegada))
                                        .addComponent(label_numeracaoroleta)
                                        .addComponent(jtextfield_numeracaoroleta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(label_lancamento)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_lancamento)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_horariochegada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtextfield_horariochegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_numeracaoroleta)
                                .addGap(3, 3, 3)
                                .addComponent(jtextfield_numeracaoroleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_horarioonibus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextfield_numeroonibus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jradio_houvereclamacao)
                            .addComponent(label_quantas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextfield_quantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jbutton_lancar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfield_numeroonibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_numeroonibusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_numeroonibusActionPerformed

    private void jtextfield_numeracaoroletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_numeracaoroletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_numeracaoroletaActionPerformed

    private void jradio_houvereclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradio_houvereclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradio_houvereclamacaoActionPerformed

    private void jbutton_lancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_lancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_lancarActionPerformed

    private void jtextfield_quantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_quantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_quantasActionPerformed

    private void jtextfield_horariochegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_horariochegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_horariochegadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancamentoFiscalFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancamentoFiscalFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancamentoFiscalFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancamentoFiscalFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LancamentoFiscalFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jbutton_lancar;
    private javax.swing.JRadioButton jradio_houvereclamacao;
    private javax.swing.JTextField jtextfield_horariochegada;
    private javax.swing.JTextField jtextfield_numeracaoroleta;
    private javax.swing.JTextField jtextfield_numeroonibus;
    private javax.swing.JTextField jtextfield_quantas;
    private javax.swing.JLabel label_horariochegada;
    private javax.swing.JLabel label_horarioonibus;
    private javax.swing.JLabel label_lancamento;
    private javax.swing.JLabel label_numeracaoroleta;
    private javax.swing.JLabel label_quantas;
    // End of variables declaration//GEN-END:variables

    public void lancar(Pessoa pessoa){
        getJbutton_lancar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Configuracoes configuracoes = new Configuracoes();
                if (getJradio_houvereclamacao().isSelected()){
                    int numeroOcorrencias = Integer.parseInt(getJtextfield_quantas().getText());
                    for (int i = 0; i <= numeroOcorrencias;i++ ){
                        configuracoes.telaReclamacao();
                    }
                }
                configuracoes.menu(pessoa);
                JComponent comp = (JComponent) e.getSource();
                Window win = SwingUtilities.getWindowAncestor(comp);
                win.dispose();
            }
        });

    }


    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JToggleButton getJbutton_lancar() {
        return jbutton_lancar;
    }

    public JRadioButton getJradio_houvereclamacao() {
        return jradio_houvereclamacao;
    }

    public JTextField getJtextfield_horariochegada() {
        return jtextfield_horariochegada;
    }

    public JTextField getJtextfield_numeracaoroleta() {
        return jtextfield_numeracaoroleta;
    }

    public JTextField getJtextfield_numeroonibus() {
        return jtextfield_numeroonibus;
    }

    public JTextField getJtextfield_quantas() {
        return jtextfield_quantas;
    }

    public JLabel getLabel_horariochegada() {
        return label_horariochegada;
    }

    public JLabel getLabel_horarioonibus() {
        return label_horarioonibus;
    }

    public JLabel getLabel_lancamento() {
        return label_lancamento;
    }

    public JLabel getLabel_numeracaoroleta() {
        return label_numeracaoroleta;
    }

    public JLabel getLabel_quantas() {
        return label_quantas;
    }
}
