/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.uva.sga.visao;

import br.uva.sga.modelo.Pessoa;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author 20212101161
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_verificaronibus = new javax.swing.JLabel();
        jtextfield_lancar = new javax.swing.JButton();
        jtextfield_verificar = new javax.swing.JButton();
        jtextfield_sair = new javax.swing.JButton();
        jlabel_quemestalogado = new javax.swing.JLabel();
        jbutton_atualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_verificaronibus.setText("Deseja verificar os ônibus, lançar ou sair?");
        label_verificaronibus.setName("label_verificaronibus"); // NOI18N

        jtextfield_lancar.setText("Lançar");
        jtextfield_lancar.setName("jtextfield_lancar"); // NOI18N
        jtextfield_lancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_lancarActionPerformed(evt);
            }
        });

        jtextfield_verificar.setLabel("Verificar");
        jtextfield_verificar.setName("jtextfield_verificar"); // NOI18N
        jtextfield_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_verificarActionPerformed(evt);
            }
        });

        jtextfield_sair.setLabel("Sair");
        jtextfield_sair.setName("jtextfield_sair"); // NOI18N

        jlabel_quemestalogado.setText("Place Holder");
        jlabel_quemestalogado.setName("jlabel_quemestalogado"); // NOI18N

        jbutton_atualizar.setText("Atualizar");
        jbutton_atualizar.setName("jbutton_atualizar"); // NOI18N
        jbutton_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_atualizarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/paulitos/Documents/Cursos/Cursos_Backup_30-04-22/Faculdade/3º periodo/POO/A4_POO/Trabalho_POO_Versão_Final/mavenproject1/Funcionarios-main/src/main/java/br/uva/sga/visao/Icones/PaulitosBUS_semFundo.png"));

        labelCargo.setText("agora vc vai terstar essa versao do progama ");
        labelCargo.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_verificaronibus)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbutton_atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtextfield_lancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtextfield_sair)
                                    .addComponent(jtextfield_verificar)))
                            .addComponent(jlabel_quemestalogado)
                            .addComponent(labelCargo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlabel_quemestalogado)
                .addGap(18, 18, 18)
                .addComponent(labelCargo)
                .addGap(28, 28, 28)
                .addComponent(label_verificaronibus)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextfield_lancar)
                    .addComponent(jtextfield_verificar))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutton_atualizar)
                    .addComponent(jtextfield_sair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfield_lancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_lancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_lancarActionPerformed

    private void jtextfield_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_verificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_verificarActionPerformed

    private void jbutton_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_atualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbutton_atualizar;
    private javax.swing.JLabel jlabel_quemestalogado;
    private javax.swing.JButton jtextfield_lancar;
    private javax.swing.JButton jtextfield_sair;
    private javax.swing.JButton jtextfield_verificar;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel label_verificaronibus;
    // End of variables declaration//GEN-END:variables

    public void view(Pessoa pessoa){
        String texto_logado = "Bem-vindo ";
        String texto_cargo = "Seu cargo: ";
        texto_cargo += pessoa.getCargo();
        texto_logado += pessoa.getNome();
        getJlabel_quemestalogado().setText(texto_logado);
        getLabelCargo().setText(texto_cargo);

    }

    public void atualizar(Pessoa pessoa){
        getJbutton_atualizar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Configuracoes configuracoes = new Configuracoes();
                configuracoes.atualizarDados(pessoa);
                JComponent comp = (JComponent) e.getSource();
                Window win = SwingUtilities.getWindowAncestor(comp);
                win.dispose();
            }
        });


    }

    public void sair(){
        getJtextfield_sair().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });

    }

    public void verificar(Pessoa pessoa){
        getJtextfield_verificar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Configuracoes configuracoes = new Configuracoes();
                configuracoes.onibusRodando(pessoa);
                JComponent comp = (JComponent) e.getSource();
                Window win = SwingUtilities.getWindowAncestor(comp);
                win.dispose();
            }
        });
    }

    public void lancar(Pessoa pessoa){
        getJtextfield_lancar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (pessoa.getCargo().equals("Fiscal")){
                    Configuracoes configuracoes = new Configuracoes();
                    configuracoes.telaLancamentoInicio(pessoa);
                    JComponent comp = (JComponent) e.getSource();
                    Window win = SwingUtilities.getWindowAncestor(comp);
                    win.dispose();
                }else{
                    Configuracoes configuracoes = new Configuracoes();
                    configuracoes.telaLancamentoFinal(pessoa);
                    JComponent comp = (JComponent) e.getSource();
                    Window win = SwingUtilities.getWindowAncestor(comp);
                    win.dispose();
                }

            }
        });
    }

    public JLabel getLabelCargo() {
        return labelCargo;
    }

    public void setJlabel_quemestalogado(JLabel jlabel_quemestalogado) {
        this.jlabel_quemestalogado = jlabel_quemestalogado;
    }

    public JButton getJbutton_atualizar() {
        return jbutton_atualizar;
    }

    public JLabel getJlabel_quemestalogado() {
        return jlabel_quemestalogado;
    }

    public JButton getJtextfield_lancar() {
        return jtextfield_lancar;
    }

    public JButton getJtextfield_sair() {
        return jtextfield_sair;
    }

    public JButton getJtextfield_verificar() {
        return jtextfield_verificar;
    }

    public JLabel getLabel_verificaronibus() {
        return label_verificaronibus;
    }
}
