/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.uva.sga.visao;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author 20212101161
 */
public class Reclamacao extends javax.swing.JFrame {

    /**
     * Creates new form Reclamacao
     */
    public Reclamacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_reclamacaocliente = new javax.swing.JLabel();
        label_numeracaoonibus = new javax.swing.JLabel();
        jtextfield_numeracaoonibus = new javax.swing.JTextField();
        label_reclamacao = new javax.swing.JLabel();
        jtextfield_reclamacao = new javax.swing.JTextField();
        label_ocorrencia = new javax.swing.JLabel();
        jtextfield_ocorrencia = new javax.swing.JTextField();
        jbutton_lancar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N

        label_reclamacaocliente.setText("RECLAMAÇÔES CLIENTE");
        label_reclamacaocliente.setName("label_reclamacaocliente"); // NOI18N

        label_numeracaoonibus.setText("Número do ônibus:");
        label_numeracaoonibus.setName("label_numeracaoonibus"); // NOI18N

        jtextfield_numeracaoonibus.setName("jtextfield_numeracaoonibus"); // NOI18N
        jtextfield_numeracaoonibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_numeracaoonibusActionPerformed(evt);
            }
        });

        label_reclamacao.setText("Reclamação:");
        label_reclamacao.setName("label_reclamacao"); // NOI18N

        jtextfield_reclamacao.setName("jtextfield_reclamacao"); // NOI18N
        jtextfield_reclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_reclamacaoActionPerformed(evt);
            }
        });

        label_ocorrencia.setText("Ocorrência");
        label_ocorrencia.setName("label_ocorrencia"); // NOI18N

        jtextfield_ocorrencia.setName("jtextfield_ocorrencia"); // NOI18N
        jtextfield_ocorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_ocorrenciaActionPerformed(evt);
            }
        });

        jbutton_lancar.setText("Lançar");
        jbutton_lancar.setName("jbutton_lancar"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/paulitos/Documents/Cursos/Cursos_Backup_30-04-22/Faculdade/3º periodo/POO/A4_POO/Trabalho_POO_Versão_Final/mavenproject1/Funcionarios-main/src/main/java/br/uva/sga/visao/Icones/PaulitosBUS_semFundo.png"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jbutton_lancar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtextfield_reclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_ocorrencia)
                                    .addComponent(jtextfield_ocorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_reclamacao)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtextfield_numeracaoonibus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_numeracaoonibus)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_reclamacaocliente)
                        .addGap(124, 124, 124))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label_reclamacaocliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_numeracaoonibus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtextfield_numeracaoonibus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_ocorrencia))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtextfield_ocorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_reclamacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtextfield_reclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jbutton_lancar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfield_numeracaoonibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_numeracaoonibusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_numeracaoonibusActionPerformed

    private void jtextfield_reclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_reclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_reclamacaoActionPerformed

    private void jtextfield_ocorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_ocorrenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_ocorrenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reclamacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reclamacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbutton_lancar;
    private javax.swing.JTextField jtextfield_numeracaoonibus;
    private javax.swing.JTextField jtextfield_ocorrencia;
    private javax.swing.JTextField jtextfield_reclamacao;
    private javax.swing.JLabel label_numeracaoonibus;
    private javax.swing.JLabel label_ocorrencia;
    private javax.swing.JLabel label_reclamacao;
    private javax.swing.JLabel label_reclamacaocliente;
    // End of variables declaration//GEN-END:variables

    public void lancar(){
        getJbutton_lancar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Configuracoes configuracoes = new Configuracoes();
                JComponent comp = (JComponent) e.getSource();
                Window win = SwingUtilities.getWindowAncestor(comp);
                win.dispose();

            }
        });

    }


    public JButton getJbutton_lancar() {
        return jbutton_lancar;
    }

    public JTextField getJtextfield_numeracaoonibus() {
        return jtextfield_numeracaoonibus;
    }

    public JTextField getJtextfield_ocorrencia() {
        return jtextfield_ocorrencia;
    }

    public JTextField getJtextfield_reclamacao() {
        return jtextfield_reclamacao;
    }

    public JLabel getLabel_numeracaoonibus() {
        return label_numeracaoonibus;
    }

    public JLabel getLabel_ocorrencia() {
        return label_ocorrencia;
    }

    public JLabel getLabel_reclamacao() {
        return label_reclamacao;
    }

    public JLabel getLabel_reclamacaocliente() {
        return label_reclamacaocliente;
    }
}
