/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.uva.sga.visao;

import br.uva.sga.controle.dao.FiscalDAO;
import br.uva.sga.controle.dao.FiscalGaragemDAO;
import br.uva.sga.controle.dao.PessoaDAO;
import br.uva.sga.modelo.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author lele2
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_digiteinformacao = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_telefone = new javax.swing.JLabel();
        jtextfield_digitenome = new javax.swing.JTextField();
        jtextfield_digitetelefone = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        jtextfield_email = new javax.swing.JTextField();
        label_senha = new javax.swing.JLabel();
        label_idade = new javax.swing.JLabel();
        jtextfield_digiteidade = new javax.swing.JTextField();
        label_cargo = new javax.swing.JLabel();
        jradio_fiscal = new javax.swing.JRadioButton();
        jradio_fiscalgaragem = new javax.swing.JRadioButton();
        jbutton_confirmar = new javax.swing.JButton();
        jtextfield_digitesenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_digiteinformacao.setText("DIGITE AS INFORMAÇÕES AQUI");
        label_digiteinformacao.setName("label_digiteinformacao"); // NOI18N

        label_nome.setText("Nome");
        label_nome.setName("label_nome"); // NOI18N

        label_telefone.setText("Telefone");
        label_telefone.setName("label_telefone"); // NOI18N

        jtextfield_digitenome.setName("jtextfield_digitenome"); // NOI18N
        jtextfield_digitenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_digitenomeActionPerformed(evt);
            }
        });

        jtextfield_digitetelefone.setName("jtextfield_digitetelefone"); // NOI18N
        jtextfield_digitetelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_digitetelefoneActionPerformed(evt);
            }
        });

        label_email.setText("Email");
        label_email.setName("label_email"); // NOI18N

        jtextfield_email.setName("jtextfield_email"); // NOI18N
        jtextfield_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_emailActionPerformed(evt);
            }
        });

        label_senha.setText("Senha");
        label_senha.setName("label_senha"); // NOI18N

        label_idade.setText("Idade");
        label_idade.setName("label_idade"); // NOI18N

        jtextfield_digiteidade.setName("jtextfield_digiteidade"); // NOI18N
        jtextfield_digiteidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_digiteidadeActionPerformed(evt);
            }
        });

        label_cargo.setText("Cargo");
        label_cargo.setName("label_cargo"); // NOI18N

        jradio_fiscal.setText("Fiscal");
        jradio_fiscal.setName("jradio_fiscal"); // NOI18N
        jradio_fiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradio_fiscalActionPerformed(evt);
            }
        });

        jradio_fiscalgaragem.setText("Fiscal Garagem");
        jradio_fiscalgaragem.setName("jradio_fiscalgaragem"); // NOI18N
        jradio_fiscalgaragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradio_fiscalgaragemActionPerformed(evt);
            }
        });

        jbutton_confirmar.setText("Confirmar");
        jbutton_confirmar.setName("jbutton_confirmar"); // NOI18N

        jtextfield_digitesenha.setName("jtextfield_digitesenha"); // NOI18N
        jtextfield_digitesenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_digitesenhaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/paulitos/Documents/Cursos/Cursos_Backup_30-04-22/Faculdade/3º periodo/POO/A4_POO/Trabalho_POO_Versão_Final/mavenproject1/Funcionarios-main/src/main/java/br/uva/sga/visao/Icones/PaulitosBUS_semFundo.png"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_digiteinformacao)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbutton_confirmar)
                        .addGap(161, 161, 161))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtextfield_digitenome, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jtextfield_digitetelefone)
                            .addComponent(jtextfield_email)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_telefone))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtextfield_digitesenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradio_fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextfield_digiteidade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jradio_fiscalgaragem)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_digiteinformacao)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(label_idade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextfield_digitenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextfield_digiteidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_telefone)
                    .addComponent(label_cargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextfield_digitetelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradio_fiscal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_email)
                    .addComponent(jradio_fiscalgaragem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtextfield_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtextfield_digitesenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addComponent(jbutton_confirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextfield_digitenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_digitenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_digitenomeActionPerformed

    private void jtextfield_digitetelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_digitetelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_digitetelefoneActionPerformed

    private void jtextfield_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_emailActionPerformed

    private void jtextfield_digiteidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_digiteidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_digiteidadeActionPerformed

    private void jradio_fiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradio_fiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradio_fiscalActionPerformed

    private void jradio_fiscalgaragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradio_fiscalgaragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradio_fiscalgaragemActionPerformed

    private void jtextfield_digitesenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_digitesenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_digitesenhaActionPerformed

    private void jbutton_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbutton_confirmarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutton_confirmar;
    private javax.swing.JRadioButton jradio_fiscal;
    private javax.swing.JRadioButton jradio_fiscalgaragem;
    private javax.swing.JTextField jtextfield_digiteidade;
    private javax.swing.JTextField jtextfield_digitenome;
    private javax.swing.JPasswordField jtextfield_digitesenha;
    private javax.swing.JTextField jtextfield_digitetelefone;
    private javax.swing.JTextField jtextfield_email;
    private javax.swing.JLabel label_cargo;
    private javax.swing.JLabel label_digiteinformacao;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_idade;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_senha;
    private javax.swing.JLabel label_telefone;
    // End of variables declaration//GEN-END:variables

    void enviarDados(Pessoa pessoa){
        getJbutton_confirmar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try{
                    pessoa.setIdade(Integer.parseInt(getJtextfield_digiteidade().getText()));
                    pessoa.setNome(getJtextfield_digitenome().getText());
                    pessoa.setEmail(getJtextfield_email().getText());
                    String senhaUsuario = "";
                    for(int i=0;i<getJtextfield_digitesenha().getPassword().length;i++){
                        senhaUsuario += getJtextfield_digitesenha().getPassword()[i];
                    }
                    pessoa.setSenha(senhaUsuario);
                    pessoa.setTelefone(getJtextfield_digitetelefone().getText());
                    if (getJradio_fiscal().isSelected()){
                        pessoa.setCargo("Fiscal");
                    }else{
                        pessoa.setCargo("Fiscal de Garagem");
                    }

                    PessoaDAO pessoaDAO = new PessoaDAO();
                    pessoaDAO.save(pessoa);
                    JComponent comp = (JComponent) e.getSource();
                    Window win = SwingUtilities.getWindowAncestor(comp);
                    win.dispose();

                    pessoa.setPessoa(pessoaDAO.consult(pessoa.getEmail()));

                    System.out.println(pessoa.getId_pessoa());

                    if (getJradio_fiscal().isSelected()){
                        FiscalDAO fiscalDAO = new FiscalDAO();
                        fiscalDAO.save(pessoa.getId_pessoa());
                        Configuracoes menu = new Configuracoes();
                        menu.menu(pessoa);

                    }else{
                        FiscalGaragemDAO fiscalGaragemDAO = new FiscalGaragemDAO();
                        fiscalGaragemDAO.save(pessoa.getId_pessoa());
                        Configuracoes menu = new Configuracoes();
                        menu.menu(pessoa);
                    }

                }catch(NumberFormatException error1){
                    error1.printStackTrace();
                }
            }
        });

    }





    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JButton getJbutton_confirmar() {
        return jbutton_confirmar;
    }

    public JRadioButton getJradio_fiscal() {
        return jradio_fiscal;
    }

    public JRadioButton getJradio_fiscalgaragem() {
        return jradio_fiscalgaragem;
    }

    public JTextField getJtextfield_digiteidade() {
        return jtextfield_digiteidade;
    }

    public JTextField getJtextfield_digitenome() {
        return jtextfield_digitenome;
    }

    public JPasswordField getJtextfield_digitesenha() {
        return jtextfield_digitesenha;
    }

    public JTextField getJtextfield_digitetelefone() {
        return jtextfield_digitetelefone;
    }

    public JTextField getJtextfield_email() {
        return jtextfield_email;
    }

    public JLabel getLabel_cargo() {
        return label_cargo;
    }

    public JLabel getLabel_digiteinformacao() {
        return label_digiteinformacao;
    }

    public JLabel getLabel_email() {
        return label_email;
    }

    public JLabel getLabel_idade() {
        return label_idade;
    }

    public JLabel getLabel_nome() {
        return label_nome;
    }

    public JLabel getLabel_senha() {
        return label_senha;
    }

    public JLabel getLabel_telefone() {
        return label_telefone;
    }
}
